Allow setting custom replacement templates
milin/giticket pull request #4
Opened 2019-01-23 17:07 UTC by speshak

This allows adjusting where in the message the ticket number is added.

2019-01-24 23:26 UTC, milin commented
Thanks for the pr. The custom template will be useful. Can you take a look at why the tests are failing?

2019-01-25 02:50 UTC, speshak commented
Yeah, I'll give those failures a look.

2019-01-25 16:28 UTC, milin commented on giticket/giticket.py
> +            new_commit_msg = format_string.format(ticket=ticket, commit_msg=commit_msg)
Can you update to 
```
new_commit_msg = format_string.format(ticket=ticket, commit_msg=commit_msg.strip())
```

Currently `commit-msg` has a newline character which makes the commit message and ticket be in two separate lines, when --format is passed in.

```
Date:   Fri Jan 25 11:18:02 2019 -0500

    test 
     JIRA-7633
```

2019-01-25 16:28 UTC, milin requested changes
Minor change required

2019-01-25 16:35 UTC, speshak commented on giticket/giticket.py
> +            new_commit_msg = format_string.format(ticket=ticket, commit_msg=commit_msg)
Doh! My immediate use case was for simple single line commit messages.  I'm going to think about this a little bit and get a better solution put together.  My initial thought is to split `commit_msg` into `commit_subject` and `commit_body` tokens.  Your original format would be represented as:

    {ticket} {commit_subject}
    {commit_body}

And my intent would be:

    {commit_subject} {ticket}
    {commit_body}

2019-04-23 15:05 UTC, Rictus commented
Hello
I'm also interested in this pull request, any update on when it will merge in ?

2019-04-23 17:03 UTC, milind-shakya-sp commented
@Rictus looks like there was a slight minor issue. I can add a slight change on top of @speshak 's changes and we can have a custom template passed in.

2019-04-23 17:47 UTC, milind-shakya-sp commented
@Rictus @speshak https://github.com/milin/giticket/commit/65ce90fb60fea9fb40c9da8fc045a86afdb76601 should now do the needful I think.

2019-04-23 17:48 UTC, milind-shakya-sp commented
Closing in favor of https://github.com/milin/giticket/pull/5

2019-04-23 17:48 UTC, closed without merging

2019-04-23 18:14 UTC, speshak commented
👍 I forgot all about this PR.  Thanks for getting my rough idea cleaned up @Rictus & @milind-shakya-sp